mysql:
  host: 127.0.0.1
  port: 3306
  config: ""
  db: gvb_db
  user: root
  password: weijia123
  log_level: dev
logger:
  level: info
  prefix: '[gopher_project]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8888
  env: release
site_info:
  created_at: "2023-04-05"
  bei_an: 皖ICP备2022012261号
  title: GopherBlog | 个人博客
  qq_image: xxx
  version: 2.0.0
  email: 2112025700@qq.com
  wechat_image: xxx
  name: 永不退场的闯关族
  job: 立志成为全栈开发工程师的研究僧
  addr: 中国·重庆
  slogan: 我们都活在阴沟里，但仍有人仰望星空！！！
  slogan_en: We all live in the gutter, but there are still people looking up at the
    stars.
  web: http://www.gopher.fit/
  gitee: https://gitee.com/wei_jia0826
  github: xxx
  csdn: https://woniu.blog.csdn.net/
qq:
  app_id: xx
  key: xx
  redirect: xx
qi_niu:
  access_key: UMM-xx-FdRIf-xx
  secret_key: xx
  bucket: gopher-blog
  cdn: xx
  zone: xx
  size: 5
email:
  host: smtp.qq.tom
  port: 465
  user: 2112025700@qq.com
  password: xxx
  default_from_email: GopherBlog
  use_ssl: false
  use_tls: false
jwt:
  secret: xxx
  expires: 48
  issuer: xx
